### ISSUE TITLE
After partial training with global is complete, an error is reported when the model is called

### ISSUE THREAD

**Issue by Star-Chou** [li-ronghui/LODGE#10]
Traceback (most recent call last):
  File "infer_lodge.py", line 340, in <module>
    test(cfg)
  File "infer_lodge.py", line 180, in test
    model_coarse.load_state_dict(state_dict, strict=True)
  File "/mnt/inais/data1/syp/LODGE/dld/models/modeltype/base.py", line 208, in load_state_dict
    super().load_state_dict(state_dict, strict)
  File "/root/miniconda3/envs/lodge1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Global_Module:
	size mismatch for DanceDecoder.null_cond_embed: copying a param with shape torch.Size([1, 256, 512]) from checkpoint, the shape in current model is torch.Size([1, 1024, 512]).
	size mismatch for diffusion.model.null_cond_embed: copying a param with shape torch.Size([1, 256, 512]) from checkpoint, the shape in current model is torch.Size([1, 1024, 512]).
	size mismatch for diffusion.master_model.null_cond_embed: copying a param with shape torch.Size([1, 256, 512]) from checkpoint, the shape in current model is torch.Size([1, 1024, 512])

**Comment by li-ronghui** [comment]
It seems that your trained Global Diffusion's length is 512, but the infer_lodge's setting is 1024.
You can set the FINEDANCE.full_seq_len as 1024 when traing the Global Diffusion.

**Comment by xiaxinyu20020718** [comment]
I'm having the same problem, is there a solution?
