### ISSUE TITLE
Soft Diffusion Guidance

### ISSUE THREAD

**Issue by mucunzhuzhu** [li-ronghui/LODGE#12]
在Local Module.py的render_sample函数中，为什么Soft Diffusion Guidance是给28到336帧，60到68帧，156到164帧，188到196帧赋值，不应该根据音乐提取的beat来确定帧的位置吗？
![image](https://github.com/li-ronghui/LODGE/assets/126659167/9f246620-296b-4ba0-b70a-8c3a6341302b)

**Comment by li-ronghui** [comment]
音乐中的beat是基本均匀的，和音乐的bpm有关。这些时段基本都包含了对应的beat，我们经验地采取这种设置

**Comment by richieliuse** [comment]
> 在Local Module.py的render_sample函数中，为什么Soft Diffusion Guidance是给28到336帧，60到68帧，156到164帧，188到196帧赋值，不应该根据音乐提取的beat来确定帧的位置吗？ ![image](https://private-user-images.githubusercontent.com/126659167/336096824-9f246620-296b-4ba0-b70a-8c3a6341302b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODYwMTUsIm5iZiI6MTcyNDA4NTcxNSwicGF0aCI6Ii8xMjY2NTkxNjcvMzM2MDk2ODI0LTlmMjQ2NjIwLTI5NmItNGJhMC1iNzBhLThjM2E2MzQxMzAyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxNjQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzZhOGMxNWU1MTI2YTM3MDc0NjMyNzI2MGU2YjcwOWE3OWI2ZTk0NzBhY2FkMjBmNDU5ZmU0MTY3YmFkOTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmIMmOhZsAeS3WnjXSLLrxOWecGU-vvewYyh_m6zl0s)

可以留个联系邮箱吗，我也遇到了一些问题想交流一下

**Comment by richieliuse** [comment]
@mucunzhuzhu 可以留个联系邮箱吗，我也遇到了一些问题想交流一下

**Comment by mucunzhuzhu** [comment]
这是我的微信号：mucunzhuzhu


***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "li-ronghui/LODGE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月20日(星期二) 下午2:52
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [li-ronghui/LODGE] Soft Diffusion Guidance (Issue #12)





 
@mucunzhuzhu 可以留个联系邮箱吗，我也遇到了一些问题想交流一下

**Comment by mucunzhuzhu** [comment]
请大家注意，这个人[richieliuse](https://github.com/richieliuse)是个骗子
