### ISSUE TITLE
EDGE在Finedance中的相关训练问题

### ISSUE THREAD

**Issue by YuanFeis** [li-ronghui/LODGE#19]
尊敬的李博士，您好！
感谢您卓越的论文，
在论文Table 1.中，您对EDGE在Finedance中的指标进行了列举，有一些问题向您请教：
1. edge的分片长度~
2. edge的训练中是否使用了jukebox~
3. edge在finedance中训练时使用的骨骼数~
再次为打扰您感到抱歉。

**Comment by li-ronghui** [comment]
你好，感谢关注！
1. 分片长度为128帧
2. 没有用jukebox，用的是与Lodge相同的35维music feature
3. 与Lodge一致，采用22个骨骼

**Comment by YuanFeis** [comment]
感谢您的回复！
祝工作顺利，万事顺意~
