### ISSUE TITLE
Where can I get NORMAL_new.obj file

### ISSUE THREAD

**Issue by plyfager** [li-ronghui/LODGE#2]
Thanks for sharing your great job! 
I'm trying to render some examples, however, when I run render.py, the file '/data2/lrh/floor/NORMAL_new.obj' is not found. Could you kindly provide it or tell me where to get it?  @li-ronghui

**Comment by li-ronghui** [comment]
Good issue！
I just uploaded the NORMAL_new.obj file to the data directory.
Now you can get it from this repo directly : )
