### ISSUE TITLE
渲染时报错：/data/human/datasets/smpl_model/smplh/SMPLH_MALE.pkl does not exist!

### ISSUE THREAD

**Issue by Malacca1211** [li-ronghui/LODGE#21]
你好，我在尝试复现您的工作时在渲染步骤遇见报错：
```
~/LODGE$ python render.py --modir /home/LODGE/data/finedance/motion
0
209.npy
Traceback (most recent call last):
  File "render.py", line 412, in <module>
    visualizer = MovieMaker(save_path=save_path)
  File "render.py", line 80, in __init__
    self.smplh = SMPLH(SMPLH_path, use_pca=False, flat_hand_mean=True)
  File "/home/xietong/miniconda3/envs/lodge/lib/python3.8/site-packages/smplx/body_models.py", line 575, in __init__
    assert osp.exists(smplh_path), 'Path {} does not exist!'.format(
AssertionError: Path /data/human/datasets/smpl_model/smplh/SMPLH_MALE.pkl does not exist!
```
预训练模型和预处理数据都是直接从您提供的链接下载的，请问从哪里可以获得这个human文件夹及其路径下文件呢。
谢谢！

顺颂夏安！

**Comment by li-ronghui** [comment]
你好，smpl,smplh和smplx是三种可选的模型用于渲染。FineDance数据集是需要用smplx模型渲染的。
因此上面error中报错的smplh不是必须项。

**Comment by li-ronghui** [comment]
For easy of use, the render.py code has been updated.  :D

**Comment by Andy010902** [comment]
> 你好，smpl,smplh和smplx是三种可选的模型用于渲染。FineDance数据集是需要用smplx模型渲染的。 因此上面error中报错的smplh不是必须项。

您好，感谢您伟大的工作，基于这个问题我想问一下render.py 中的from smplx import SMPLX的smplx是什么，在哪里呢？
非常感谢！

**Comment by Ha0Tang** [comment]
你好 渲染的时候我遇到这个问题了 请问怎么解决咧？
`Traceback (most recent call last):
  File "render.py", line 405, in <module>
    visualizer = MovieMaker(save_path=save_path)
  File "render.py", line 79, in __init__
    self.smplx = SMPLX(SMPLX_path, use_pca=False, flat_hand_mean=True).eval()
  File "/miniconda3/envs/edge/lib/python3.8/site-packages/smplx/body_models.py", line 969, in __init__
    assert osp.exists(smplx_path), 'Path {} does not exist!'.format(
AssertionError: Path /data/human/datasets/smpl_model/smplx/SMPLX_NEUTRAL.npz does not exist!`
