### ISSUE TITLE
关于在自己的音频文件上进行推理测试

### ISSUE THREAD

**Issue by Malacca1211** [li-ronghui/LODGE#22]
你好，请问如果需要在自己的音频文件上进行推理测试，只需要修改infer_lodge.py里面的music_dir为自己的音频文件路径就行吗（这种方式我尝试过但没有用，具体来说我没有找到生成的motion文件）

**Comment by JThuge** [comment]
请问你解决了嘛

**Comment by aiquanpeng** [comment]
同问

**Comment by li-ronghui** [comment]
看到了挺多朋友遇到这个问题，这里统一回复一下：

infer_lodge.py是用来推理的，但是当前的配置主要是针对数据集中的音乐，
如果要用自己的音乐的话，需要改一下：
1. cfg.DEMO.use_cached_features需要设置为false，让代码从wav文件中直接用librosa提取35 dimension的music feature
2.  line293需要手动设定为genre对应的数字。目前支持的风格如下，让设置的风格和音乐接近一些，可能会效果好一些。简单地划分的话，常见的快节奏音乐可以用0-5、13、14；慢节奏音乐可以用9-12。
Genres_fd = { 
          'Breaking': 0,
          'Popping': 1,
          'Locking': 2,
          'Hiphop':3,
          'Urban':4,
          'Jazz':5,
          'jazz':5,
          'Tai':6,
          'Uighur':7,
          'Hmong':8,
          'Dai':6,
          'Wei':7,
          'Miao':8,
          'HanTang':9,
          'ShenYun':10,
          'Kun':11,
          'DunHuang':12,
          'Korean':13,
          'Choreography':14,
          'Chinese':15,
}

最后motion输出的地方应该在Line331可以看到：
https://github.com/li-ronghui/LODGE/blob/a898e5914d325ec1016302b2a7760e56437e2b9c/infer_lodge.py#L331
