### ISSUE TITLE
soft-cue guidance not work.

### ISSUE THREAD

**Issue by richieliuse** [li-ronghui/LODGE#26]
Hi,

感谢这个杰出的工作！我在使用这个代码库尝试复现论文demo的时候遇到一个问题，通过infer代码生成的动作，模型的下半身几乎没有动作，看起来像论文中对照没有使用soft-cue guidance的效果。请问是需要进行什么特别的设置或者有什么使用的技巧吗？

**Comment by li-ronghui** [comment]
模型的下半身几乎没有动作有多方面因素可能引起，如音乐较舒缓，给出了in the wild音乐等，由于训练集有限，因此LODGE难以根据in the wild音乐生成有表现力的长时舞蹈。另外如果你有改动代码， 可以检查一下soft-cue guidance的参数传递等代码部分。

一些使用技巧，可能是可以多尝试快节奏的音乐吧。由于FineDance数据集中现代歌舞（快节奏）分布较多，因此LODGE根据快节奏的音乐生成街舞等快节奏舞蹈效果会更好一些。
对于慢节奏音乐或者音乐的前奏，尾声等慢节奏部分，生成的动作可能倾向于保守，因此可以尝试渲染音乐的高潮部分或尝试更多不同的快节奏的音乐。

**Comment by richieliuse** [comment]
感谢回复！我会按这个思路做些尝试。
