### ISSUE TITLE
关于数据帧数的问题

### ISSUE THREAD

**Issue by Malacca1211** [li-ronghui/LODGE#27]
作者您好！
我注意到music_new_npy中的帧数比motion_npy_319多2帧，请问这是为什么

**Comment by Andy010902** [comment]
有的音乐特征提出来是多一帧，正常。你motion319的总帧数是多少啊，就是data_li.shape[0] (python dld/data/pre/FineDance_normalizer.py)

**Comment by Andy010902** [comment]
> > 有的音乐特征提出来是多一帧，正常。你motion319的总帧数是多少啊，就是data_li.shape[0] (python dld/data/pre/FineDance_normalizer.py)
> 
> 那我应该怎么对齐motion和music呀 谢谢大佬解答

截断，取两者最短长度，代码里写了
