### ISSUE TITLE
I got 822,177 frames from ./data/finedance/mofea319, not 831600 frames mentioned in paper?

### ISSUE THREAD

**Issue by Andy010902** [li-ronghui/LODGE#28]
Hi, @li-ronghui 
When I did python dld/data/pre/FineDance_normalizer.py to get normalizer.pth, I got 822,177 frames from ./data/finedance/mofea319(203 *.npy files), not available 831600 frames mentioned in paper.
Please tell me if there is something wrong.
Andy

**Comment by li-ronghui** [comment]
Hi, Andy, thanks for your kind issue.

When I trained the network, I noticed that some of the dances in FineDance had less motion in the begin of the music. You know that professional dancers often prefer to use the music's prelude to settle down and build emotion, therefore performing fewer movements during the begin of music, which is more pronounced in classical dance. Therefore, I cut out this part of the prelude dance to enable the network to generate more expressive actions, which may result in relatively fewer frames.

Don't worry, the features used in Lodge's training are fully consistent with the [processed motion features](https://drive.google.com/drive/folders/1cdj8YymfN1BHgggVfGaLjaa9vaEpjPzZ) we released. We also recommend directly downloading these processed features to train your model.

The 831600 frames corresponding to the origin released FineDance data. Which can be downloaded at https://drive.google.com/file/d/1zQvWG9I0H4U3Zrm8d_QD_ehenZvqfQfS/view.
