### ISSUE TITLE
How can I get label_json file?

### ISSUE THREAD

**Issue by limeverry** [li-ronghui/LODGE#33]
hello, 
First of all, thank you so much for your great work.

In my case, I want to infer and visualize the in-the-wild data I have.
But there is no label_json file that assigns the actual music to run 'infer_lodge.py'.
It seems that a genre code or style code is needed in the code, as in line 295. 

So what should I do? Can you tell me what I need to do while editing the code or creating the json file?

Thank you

**Comment by li-ronghui** [comment]
Hi, you can choose a dance genre you want to generate from 'Genres_fd' at './dld/data/FineDance_dataset.py'.

**Comment by limeverry** [comment]
Thank you very much :)
