### ISSUE TITLE
关于镜像操作的问题

### ISSUE THREAD

**Issue by dsdf783** [li-ronghui/LODGE#7]
为什么要对soft-cue key motions进行镜像操作，这步操作和第二点编舞规则的联系是什么？

**Comment by li-ronghui** [comment]
这里的insights出自ChoreoMaster: Choreography -Oriented Music Driven Dance Synthesis
文中提到：

> The organization of a dance should be coordinated with the structure of the corresponding music, e.g., repeated musical phrases (verse and chorus) are typically associated with repeated movements, while identical meters in a phrase often correspond to symmetrical movements.

因此我们希望生成的长序列舞蹈也具有一些结构上的相似性和对称性，所以进行了镜像操作
