### ISSUE TITLE
Inference by using in-the-wild speech audio

### ISSUE THREAD

**Issue by jiaqiAA** [li-ronghui/LODGE#8]
Could you provide a script that inference by using in-the-wild speech audio?

**Comment by li-ronghui** [comment]
Hi, you can use the 'infer_lodge.py' to inference using in-the-wild speech audio.
Please put your audio in the 'music_dir' and do the inference command.

**Comment by li-ronghui** [comment]
Our code is designed for music input and has not tried speech input.
