### ISSUE TITLE
Experiments based on AIST++ dataset?

### ISSUE THREAD

**Issue by mucunzhuzhu** [li-ronghui/LODGE#9]
Can you provide the relevant code for the experiments based on AIST++ dataset?

**Comment by li-ronghui** [comment]
Hi, thanks for attention!
Our task focuses on long-sequence dance generation, but the dance in AIST++ are divided into short clips of only a few seconds, making them unsuitable for our algorithm's requirements. 
For instance, the experimental parameters of Local Diffusion generate approximately 8 seconds of dance per sequence, but many splited AIST++ dance segments are shorter than 8 seconds.
